= Contributing to the Git Plugin

The git plugin implements the https://plugins.jenkins.io/scm-api[Jenkins SCM API].
Refer to the SCM API documentation for https://github.com/jenkinsci/scm-api-plugin/blob/master/docs/implementation.adoc#naming-your-plugin[plugin naming conventions]
and for the https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#add-to-core-or-create-extension-plugin[preferred locations of new functionality].

Plugin source code is hosted on https://github.com/jenkinsci/git-plugin[GitHub].
New feature proposals and bug fix proposals should be submitted as https://help.github.com/articles/creating-a-pull-request[GitHub pull requests].
Your pull request will be evaluated by the https://ci.jenkins.io/job/Plugins/job/git-plugin/[Jenkins job].

Before submitting your change, please assure that you've added tests which verify your change.
There have been many developers involved in the git plugin and there are many, many users who depend on the git plugin.
Tests help us assure that we're delivering a reliable plugin, and that we've communicated our intent to other developers as executable descriptions of plugin behavior.

Code coverage reporting is available as a maven target.
Please try to improve code coverage with tests when you submit.

* `mvn -P enable-jacoco clean install jacoco:report` to report code coverage

Please don't introduce new spotbugs output.

* `mvn spotbugs:check` to analyze project using [Spotbugs](https://spotbugs.github.io/)
* `mvn spotbugs:gui` to review Spotbugs report using GUI

Code formatting in the git plugin varies between files.
Try to maintain reasonable consistency with the existing files where feasible.
Please don't perform wholesale reformatting of a file without discussing with the current maintainers.
New code should follow the https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#code-style-guidelines[SCM API code style guidelines].
