= Contributing to the Git Plugin

The git plugin implements the https://plugins.jenkins.io/scm-api[Jenkins SCM API].
Refer to the SCM API documentation for https://github.com/jenkinsci/scm-api-plugin/blob/master/docs/implementation.adoc#naming-your-plugin[plugin naming conventions]
and for the https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#add-to-core-or-create-extension-plugin[preferred locations of new functionality].

Plugin source code is hosted on https://github.com/jenkinsci/git-plugin[GitHub].
New feature proposals and bug fix proposals should be submitted as https://help.github.com/articles/creating-a-pull-request[GitHub pull requests].
Your pull request will be evaluated by the https://ci.jenkins.io/job/Plugins/job/git-plugin/[Jenkins job].

Before submitting your change, please assure that you've added tests which verify your change.
There have been many developers involved in the git plugin and there are many, many users who depend on the git plugin.
Tests help us assure that we're delivering a reliable plugin, and that we've communicated our intent to other developers as executable descriptions of plugin behavior.

Compile and test the git plugin with the command:

* `mvn clean verify`

Compile the git plugin without running tests using the command:

* `mvn clean -DskipTests verify`

Code coverage reporting is available as a maven target.
Please try to improve code coverage with tests when you submit.

* `mvn -P enable-jacoco clean install jacoco:report` to report code coverage

Please don't introduce new spotbugs output.

* `mvn spotbugs:check` to analyze project using https://spotbugs.github.io/[Spotbugs].
* `mvn spotbugs:gui` to review Spotbugs report using GUI

Code formatting in the git plugin varies between files.
Try to maintain reasonable consistency with the existing files where feasible.
Please don't perform wholesale reformatting of a file without discussing with the current maintainers.
New code should follow the https://github.com/jenkinsci/scm-api-plugin/blob/master/CONTRIBUTING.md#code-style-guidelines[SCM API code style guidelines].

**Beware:** when building locally, some global gitconfig settings can make tests fail. 
Currently they expect the default branch to be called `master`.
If the default branch has been set to another value than master, it should be temporarily disabled.
This is done by adding **#** before `defaultBranch = main` in the `init` section 
of the `.gitconfig` file (located in your home directory).

There are enough automated tests in the plugin that it can require more than 60 minutes to complete testing on slower hardware.
The `buildPlugin()` Pipeline shared library limits plugin jobs to 60 minutes and fails them if they take more than 60 minutes.
The longest running automated tests have been adapted to have an upper bound on their runtime.
Once the runtime set in those long running tests has been reached, new tests in that test class are skipped with the message that the max time was exceeded.
Those tests have also been adapted to execute the individuals tests in those classes in random order.
By executing the tests in random order, it increases the chances that at least one of the parallel branches of `buildPlugin()` will execute each test in the long running test classes.

[[pull-request-review]]
== Reviewing Pull Requests

Maintainers triage pull requests by reviewing them and by assigning labels.
Release drafter uses the labels to automate link:https://github.com/jenkinsci/git-plugin/releases[release notes].
link:Priorities.adoc#git-plugin-development-priorities[Prioritization] uses the labels to group relevant pull requests.

Others are encouraged to review pull requests, test pull request builds, and report their results in the pull request.
Refer to the link:Priorities.adoc#priorities[maintainer's priority list] for topics the plugin maintainers are considering.

=== Testing a Pull Request Build

Pull request builds merge the most recent changes from their target branch with the change proposed in the pull request.
They can be downloaded from ci.jenkins.io and used to test the pull request.
Steps to test a pull request build are:

. *Find the pull request on link:https://github.com/jenkinsci/git-plugin/pulls[GitHub]* - for example, link:https://github.com/jenkinsci/git-plugin/pull/676[pull request 676]
. *Find the link:https://ci.jenkins.io/job/Plugins/job/git-plugin/view/change-requests/[ci.jenkins.io] artifacts for that pull request* from the link to the link:https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-676/lastSuccessfulBuild/[artifacts in the Jenkins job] in "*Show all checks*"
. *Copy the URL of the `hpi` file* into the "Advanced settings of the Plugin Manager
. *Restart your Jenkins* and you're ready to test

[[bug-triage]]
== Reviewing Bug Reports

Git plugin bug reports are assigned to one of the maintainers by default.
link:https://issues.jenkins.io/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open)%20AND%20component%20%3D%20git-plugin%20and%20assignee%20in%20(rsandell%2Cmarkewaite%2Cfcojfernandez)[Open bug reports] assigned to a maintainer are assumed to have not been reviewed.
When a maintainer completes review of an issue, they include a comment on the bug report and set the 'Assignee' to 'Unassigned'.

Others are welcome to review bug reports, comment on the results of the review, and set the 'Assignee' to 'Unassigned'.
Typical bug review tasks include:

* Review summary and description
* Attempt to duplicate the issue
* Add a comment with results of the attempt to duplicate the issue
